export const LANGUAGES = {
  af: { code: 'af', name: 'Afrikaans', locale: 'af-ZA', speechLocale: 'af-ZA' },
  ar: { code: 'ar', name: 'Arabic', locale: 'ar-SA', speechLocale: 'ar-SA' },
  bn: { code: 'bn', name: 'Bengali', locale: 'bn-BD', speechLocale: 'bn-BD' },
  cs: { code: 'cs', name: 'Czech', locale: 'cs-CZ', speechLocale: 'cs-CZ' },
  da: { code: 'da', name: 'Danish', locale: 'da-DK', speechLocale: 'da-DK' },
  de: { code: 'de', name: 'German', locale: 'de-DE', speechLocale: 'de-DE' },
  el: { code: 'el', name: 'Greek', locale: 'el-GR', speechLocale: 'el-GR' },
  en: { code: 'en', name: 'English', locale: 'en-US', speechLocale: 'en-US' },
  es: { code: 'es', name: 'Spanish', locale: 'es-ES', speechLocale: 'es-ES' },
  fa: { code: 'fa', name: 'Persian', locale: 'fa-IR', speechLocale: 'fa-IR' },
  fi: { code: 'fi', name: 'Finnish', locale: 'fi-FI', speechLocale: 'fi-FI' },
  fr: { code: 'fr', name: 'French', locale: 'fr-FR', speechLocale: 'fr-FR' },
  he: { code: 'he', name: 'Hebrew', locale: 'he-IL', speechLocale: 'he-IL' },
  hi: { code: 'hi', name: 'Hindi', locale: 'hi-IN', speechLocale: 'hi-IN' },
  id: { code: 'id', name: 'Indonesian', locale: 'id-ID', speechLocale: 'id-ID' },
  it: { code: 'it', name: 'Italian', locale: 'it-IT', speechLocale: 'it-IT' },
  ja: { code: 'ja', name: 'Japanese', locale: 'ja-JP', speechLocale: 'ja-JP' },
  ko: { code: 'ko', name: 'Korean', locale: 'ko-KR', speechLocale: 'ko-KR' },
  ms: { code: 'ms', name: 'Malay', locale: 'ms-MY', speechLocale: 'ms-MY' },
  nl: { code: 'nl', name: 'Dutch', locale: 'nl-NL', speechLocale: 'nl-NL' },
  no: { code: 'no', name: 'Norwegian', locale: 'nb-NO', speechLocale: 'nb-NO' },
  pl: { code: 'pl', name: 'Polish', locale: 'pl-PL', speechLocale: 'pl-PL' },
  pt: { code: 'pt', name: 'Portuguese', locale: 'pt-BR', speechLocale: 'pt-BR' },
  ro: { code: 'ro', name: 'Romanian', locale: 'ro-RO', speechLocale: 'ro-RO' },
  ru: { code: 'ru', name: 'Russian', locale: 'ru-RU', speechLocale: 'ru-RU' },
  sv: { code: 'sv', name: 'Swedish', locale: 'sv-SE', speechLocale: 'sv-SE' },
  th: { code: 'th', name: 'Thai', locale: 'th-TH', speechLocale: 'th-TH' },
  tr: { code: 'tr', name: 'Turkish', locale: 'tr-TR', speechLocale: 'tr-TR' },
  uk: { code: 'uk', name: 'Ukrainian', locale: 'uk-UA', speechLocale: 'uk-UA' },
  ur: { code: 'ur', name: 'Urdu', locale: 'ur-PK', speechLocale: 'ur-PK' },
  vi: { code: 'vi', name: 'Vietnamese', locale: 'vi-VN', speechLocale: 'vi-VN' },
  zh: { code: 'zh', name: 'Chinese', locale: 'zh-CN', speechLocale: 'zh-CN' },
}

export const LANGUAGE_OPTIONS = Object.values(LANGUAGES)

export const DEFAULT_DIRECTION = {
  source: LANGUAGES.en.code,
  target: LANGUAGES.hi.code,
}
